#pragma once
#include "HelpTools.h"

enum class ErrorTypes : signed_int8_t
{
	NULL_STATE = -1,
	TOTAL_ERROR,
	IS_OK,
	NO_MONITORS,
	FEW_MONITORS,
	MONITOR_MIRROR_DRIVER,
	INCORRECT_LINK,
	REMOTE_SESSION,
	VIRTUAL_SESSION,
	WEBCAM_CONNECTION_ERROR,
	CREATE_BMP_FAILED,
	SET_HOOK_ERROR,
	AUTH_ERROR,
	TEST_PASS_ERROR,
	NULLPTR_STATE,
	CATCH_EXCEPTION,
	INVALID_CAPTION,
	INVALID_CLASS_NAME
};

