#pragma once

enum class ErrorTypes : unsigned short int
{
	TOTAL_ERROR,
	NO_MONITORS,
	FEW_MONITORS,
	MONITOR_MIRROR_DRIVER,
	INCORRECT_LINK,
	REMOTE_SESSION,
	VIRTUAL_SESSION,
	IS_OK,
	WEBCAM_CONNECTION_ERROR,
	CREATE_BMP_FAILED
};

